# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='randomNumber',
            field=models.IntegerField(default=48),
        ),
    ]
