# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0003_auto_20171111_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='randomNumber',
        ),
        migrations.AddField(
            model_name='myuser',
            name='random_number',
            field=models.IntegerField(default=3),
        ),
    ]
